// web/src/parent/components/TaskTypeConfigForms.tsx
import { useCallback, useEffect, useState } from 'react';
import { Input, Radio, Select, Space, Typography } from 'antd';
import type { TaskTypeValue } from '@shared/api/types';
import { FormField } from '@shared/components';

/** 类型配置（Record 形式，序列化为 JSON） */
export type TypeConfigValue = Record<string, unknown>;

/** TaskTypeConfigForms 属性 */
export interface TaskTypeConfigFormsProps {
  taskType: TaskTypeValue | '';
  onTaskTypeChange: (value: TaskTypeValue | '') => void;
  typeConfig: TypeConfigValue;
  onTypeConfigChange: (config: TypeConfigValue) => void;
}

// ---- 星期标签 ----
const WEEKDAY_LABELS: { value: number; label: string }[] = [
  { value: 1, label: '周一' },
  { value: 2, label: '周二' },
  { value: 3, label: '周三' },
  { value: 4, label: '周四' },
  { value: 5, label: '周五' },
  { value: 6, label: '周六' },
  { value: 7, label: '周日' },
];

// ---- LIMITED 子表单 ----
function LimitedConfigForm({
  config,
  onChange,
}: {
  config: TypeConfigValue;
  onChange: (cfg: TypeConfigValue) => void;
}) {
  const [startDate, setStartDate] = useState((config.start_date as string) ?? '');
  const [endDate, setEndDate] = useState((config.end_date as string) ?? '');

  useEffect(() => {
    setStartDate((config.start_date as string) ?? '');
    setEndDate((config.end_date as string) ?? '');
  }, [config.start_date, config.end_date]);

  const handleStartChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      const v = e.target.value;
      setStartDate(v);
      onChange({ start_date: v || undefined, end_date: endDate });
    },
    [endDate, onChange],
  );

  const handleEndChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      const v = e.target.value;
      setEndDate(v);
      onChange({ start_date: startDate || undefined, end_date: v });
    },
    [startDate, onChange],
  );

  return (
    <Space direction="vertical" size="small" style={{ width: '100%' }}>
      <FormField label="开始日期（可选）" htmlFor="limited-start">
        <Input id="limited-start" type="date" value={startDate} onChange={handleStartChange} />
      </FormField>
      <FormField label="结束日期" htmlFor="limited-end">
        <Input id="limited-end" type="date" value={endDate} onChange={handleEndChange} />
      </FormField>
    </Space>
  );
}

// ---- REPEAT 子表单 ----
type Frequency = 'DAILY' | 'WEEKLY' | 'MONTHLY' | 'YEARLY';

/** 从 config 中提取 trigger_day 的指定字段 */
function getTriggerField<T>(config: TypeConfigValue, key: string, fallback: T): T {
  const td = config.trigger_day;
  if (td && typeof td === 'object' && key in (td as Record<string, unknown>)) {
    return (td as Record<string, unknown>)[key] as T;
  }
  return fallback;
}

function RepeatConfigForm({
  config,
  onChange,
}: {
  config: TypeConfigValue;
  onChange: (cfg: TypeConfigValue) => void;
}) {
  const [frequency, setFrequency] = useState<Frequency>(
    (config.frequency as Frequency) ?? 'DAILY',
  );
  const [weekday, setWeekday] = useState<number | null>(
    getTriggerField<number | null>(config, 'weekday', null),
  );
  const [monthlyMode, setMonthlyMode] = useState(
    getTriggerField<string>(config, 'mode', 'FIRST_DAY'),
  );
  const [yearMonth, setYearMonth] = useState(
    String(getTriggerField<number>(config, 'month', 1)),
  );
  const [yearDay, setYearDay] = useState(
    String(getTriggerField<number>(config, 'day', 1)),
  );

  // 外部 config 变化时同步到本地状态
  useEffect(() => {
    setFrequency((config.frequency as Frequency) ?? 'DAILY');
    const td = config.trigger_day;
    if (td && typeof td === 'object') {
      const obj = td as Record<string, unknown>;
      setWeekday('weekday' in obj ? (Number(obj.weekday) || null) : null);
      setMonthlyMode('mode' in obj ? ((obj.mode as string) ?? 'FIRST_DAY') : 'FIRST_DAY');
      setYearMonth('month' in obj ? String(obj.month ?? 1) : '1');
      setYearDay('day' in obj ? String(obj.day ?? 1) : '1');
    } else {
      setWeekday(null);
      setMonthlyMode('FIRST_DAY');
      setYearMonth('1');
      setYearDay('1');
    }
  }, [config.frequency, config.trigger_day]);

  /** 根据频率和当前配置生成 typeConfig 对象 */
  function buildConfig(
    freq: Frequency,
    wd: number | null,
    mm: string,
    ym: string,
    yd: string,
  ): TypeConfigValue {
    const cfg: TypeConfigValue = { frequency: freq };
    if (freq === 'WEEKLY') {
      if (wd != null) cfg.trigger_day = { weekday: wd };
    } else if (freq === 'MONTHLY') {
      cfg.trigger_day = { mode: mm };
    } else if (freq === 'YEARLY') {
      cfg.trigger_day = { month: Number(ym), day: Number(yd) };
    }
    return cfg;
  }

  const handleFrequencyChange = useCallback(
    (v: string) => {
      const freq = v as Frequency;
      setFrequency(freq);
      onChange(buildConfig(freq, null, 'FIRST_DAY', '1', '1'));
    },
    [onChange],
  );

  const handleWeekdayChange = useCallback(
    (day: number) => {
      setWeekday(day);
      onChange(buildConfig(frequency, day, monthlyMode, yearMonth, yearDay));
    },
    [frequency, monthlyMode, yearMonth, yearDay, onChange],
  );

  const handleMonthlyModeChange = useCallback(
    (v: string) => {
      setMonthlyMode(v);
      onChange(buildConfig(frequency, weekday, v, yearMonth, yearDay));
    },
    [frequency, weekday, yearMonth, yearDay, onChange],
  );

  // 年月日变更时重新通知
  useEffect(() => {
    if (frequency === 'YEARLY') {
      onChange(buildConfig(frequency, weekday, monthlyMode, yearMonth, yearDay));
    }
  }, [frequency, yearMonth, yearDay, weekday, monthlyMode, onChange]);

  return (
    <Space direction="vertical" size="small" style={{ width: '100%' }}>
      <FormField label="频率" htmlFor="repeat-frequency">
        <Select id="repeat-frequency" value={frequency} onChange={handleFrequencyChange} style={{ width: '100%' }}>
          <Select.Option value="DAILY">每天</Select.Option>
          <Select.Option value="WEEKLY">每周</Select.Option>
          <Select.Option value="MONTHLY">每月</Select.Option>
          <Select.Option value="YEARLY">每年</Select.Option>
        </Select>
      </FormField>

      {frequency === 'WEEKLY' && (
        <fieldset>
          <Typography.Text strong style={{ display: 'block', marginBottom: 8 }}>选择星期</Typography.Text>
          <Radio.Group value={weekday} onChange={(e) => handleWeekdayChange(e.target.value)}>
            <Space wrap>
              {WEEKDAY_LABELS.map((wd) => (
                <Radio key={wd.value} value={wd.value}>
                  {wd.label}
                </Radio>
              ))}
            </Space>
          </Radio.Group>
        </fieldset>
      )}

      {frequency === 'MONTHLY' && (
        <FormField label="模式" htmlFor="repeat-monthly-mode">
          <Select id="repeat-monthly-mode" value={monthlyMode} onChange={handleMonthlyModeChange} style={{ width: '100%' }}>
            <Select.Option value="FIRST_DAY">月初</Select.Option>
            <Select.Option value="LAST_DAY">月末</Select.Option>
            <Select.Option value="MID_MONTH">月中</Select.Option>
          </Select>
        </FormField>
      )}

      {frequency === 'YEARLY' && (
        <Space>
          <FormField label="月份" htmlFor="repeat-year-month">
            <Select id="repeat-year-month" value={yearMonth} onChange={(v) => setYearMonth(v)} style={{ width: 120 }}>
              {Array.from({ length: 12 }, (_, i) => (
                <Select.Option key={i + 1} value={String(i + 1)}>
                  {i + 1} 月
                </Select.Option>
              ))}
            </Select>
          </FormField>
          <FormField label="日期" htmlFor="repeat-year-day">
            <Select id="repeat-year-day" value={yearDay} onChange={(v) => setYearDay(v)} style={{ width: 120 }}>
              {Array.from({ length: 31 }, (_, i) => (
                <Select.Option key={i + 1} value={String(i + 1)}>
                  {i + 1} 日
                </Select.Option>
              ))}
            </Select>
          </FormField>
        </Space>
      )}
    </Space>
  );
}

// ---- STANDING 子表单 ----
function StandingConfigForm({
  config,
  onChange,
}: {
  config: TypeConfigValue;
  onChange: (cfg: TypeConfigValue) => void;
}) {
  return (
    <Typography.Text type="secondary" style={{ fontSize: 12 }}>
      当前类型的重复提交控制已移至表单顶部「允许重复提交」设置。
    </Typography.Text>
  );
}

/**
 * TaskTypeConfigForms —— 任务类型选择器 + 按类型动态渲染配置子表单。
 *
 * 用法：
 * ```tsx
 * const [taskType, setTaskType] = useState<TaskTypeValue | ''>('');
 * const [typeConfig, setTypeConfig] = useState<TypeConfigValue>({});
 *
 * <TaskTypeConfigForms
 *   taskType={taskType}
 *   onTaskTypeChange={setTaskType}
 *   typeConfig={typeConfig}
 *   onTypeConfigChange={setTypeConfig}
 * />
 * ```
 */
export function TaskTypeConfigForms({
  taskType,
  onTaskTypeChange,
  typeConfig,
  onTypeConfigChange,
}: TaskTypeConfigFormsProps) {
  const handleTaskTypeChange = useCallback(
    (v: string) => {
      const value = v as TaskTypeValue | '';
      onTaskTypeChange(value);
      // 切换类型时重置配置为默认值（空字符串属性在序列化为 JSON 时会保留，故省略）
      if (value === 'LIMITED') {
        onTypeConfigChange({ end_date: '' });
      } else if (value === 'REPEAT') {
        onTypeConfigChange({ frequency: 'DAILY' });
      } else if (value === 'STANDING') {
        onTypeConfigChange({ max_submissions: null });
      } else {
        onTypeConfigChange({});
      }
    },
    [onTaskTypeChange, onTypeConfigChange],
  );

  return (
    <Space direction="vertical" size="small" style={{ width: '100%' }}>
      <FormField label="任务类型" htmlFor="task-type">
        <Select id="task-type" value={taskType} onChange={handleTaskTypeChange} style={{ width: '100%' }}>
          <Select.Option value="">选择任务类型</Select.Option>
          <Select.Option value="LIMITED">限时任务</Select.Option>
          <Select.Option value="REPEAT">重复任务</Select.Option>
          <Select.Option value="STANDING">常驻任务</Select.Option>
        </Select>
      </FormField>

      {taskType === 'LIMITED' && (
        <LimitedConfigForm config={typeConfig} onChange={onTypeConfigChange} />
      )}

      {taskType === 'REPEAT' && (
        <RepeatConfigForm config={typeConfig} onChange={onTypeConfigChange} />
      )}

      {taskType === 'STANDING' && (
        <StandingConfigForm config={typeConfig} onChange={onTypeConfigChange} />
      )}
    </Space>
  );
}

// web/apps/console/src/views/parent/components/TaskTypeConfigForms.vue
<template>
  <n-space vertical :size="12">
    <n-form-item label="任务类型" path="taskType">
      <n-select
        :value="taskType"
        :options="typeOptions"
        placeholder="选择任务类型"
        @update:value="handleTypeChange"
      />
    </n-form-item>

    <!-- 限时任务配置 -->
    <template v-if="taskType === 'LIMITED'">
      <n-form-item label="开始日期（可选）" path="limitedStart">
        <n-date-picker
          :value="limitedStartTs"
          type="date"
          style="width: 100%"
          clearable
          @update:formatted-value="(v: string | null) => emitLimited(v, limitedEnd)"
        />
      </n-form-item>
      <n-form-item label="结束日期" path="limitedEnd">
        <n-date-picker
          :value="limitedEndTs"
          type="date"
          style="width: 100%"
          clearable
          @update:formatted-value="(v: string | null) => emitLimited(limitedStart, v)"
        />
      </n-form-item>
    </template>

    <!-- 重复任务配置 -->
    <template v-else-if="taskType === 'REPEAT'">
      <n-form-item label="频率" path="frequency">
        <n-select
          :value="frequency"
          :options="frequencyOptions"
          @update:value="handleFrequencyChange"
        />
      </n-form-item>
      <n-form-item v-if="frequency === 'WEEKLY'" label="选择星期" path="weekday">
        <n-radio-group :value="weekday" @update:value="handleWeekdayChange">
          <n-space>
            <n-radio v-for="wd in weekdayLabels" :key="wd.value" :value="wd.value">
              {{ wd.label }}
            </n-radio>
          </n-space>
        </n-radio-group>
      </n-form-item>
      <n-form-item v-if="frequency === 'MONTHLY'" label="模式" path="monthlyMode">
        <n-select
          :value="monthlyMode"
          :options="monthlyModeOptions"
          @update:value="handleMonthlyModeChange"
        />
      </n-form-item>
      <n-form-item v-if="frequency === 'YEARLY'" label="触发日期" path="yearly">
        <n-space>
          <n-select
            :value="yearMonth"
            :options="monthOptions"
            style="width: 120px"
            @update:value="(v: number) => emitYearly(v, yearDay)"
          />
          <n-select
            :value="yearDay"
            :options="dayOptions"
            style="width: 120px"
            @update:value="(v: number) => emitYearly(yearMonth, v)"
          />
        </n-space>
      </n-form-item>
    </template>

    <!-- 常驻任务：无附加配置 -->
    <template v-else-if="taskType === 'STANDING'">
      <n-text depth="3" style="font-size: 12px">
        当前类型的重复提交控制已移至表单顶部「允许重复提交」设置。
      </n-text>
    </template>
  </n-space>
</template>

<script lang="ts" setup>
  import { computed, ref, watch } from 'vue';
  import { NDatePicker, NFormItem, NRadio, NRadioGroup, NSelect, NSpace, NText } from 'naive-ui';
  import type { ParentTaskType } from '../utils';

  /**
   * TaskTypeConfigForms —— 任务类型选择器 + 按类型动态渲染配置子表单。
   * 从旧版 React 组件 web/apps/console/src/parent/components/TaskTypeConfigForms.tsx 移植。
   * typeConfig 在线上序列化为 JSON 字符串，由页面层负责 stringify。
   */
  const props = defineProps<{
    taskType: ParentTaskType | '';
    typeConfig: Record<string, unknown>;
  }>();

  const emit = defineEmits<{
    (e: 'update:taskType', value: ParentTaskType | ''): void;
    (e: 'update:typeConfig', value: Record<string, unknown>): void;
  }>();

  const typeOptions = [
    { label: '选择任务类型', value: '' },
    { label: '限时任务', value: 'LIMITED' },
    { label: '重复任务', value: 'REPEAT' },
    { label: '常驻任务', value: 'STANDING' },
  ];

  const frequencyOptions = [
    { label: '每天', value: 'DAILY' },
    { label: '每周', value: 'WEEKLY' },
    { label: '每月', value: 'MONTHLY' },
    { label: '每年', value: 'YEARLY' },
  ];

  const monthlyModeOptions = [
    { label: '月初', value: 'FIRST_DAY' },
    { label: '月末', value: 'LAST_DAY' },
    { label: '月中', value: 'MID_MONTH' },
  ];

  const weekdayLabels = [
    { value: 1, label: '周一' },
    { value: 2, label: '周二' },
    { value: 3, label: '周三' },
    { value: 4, label: '周四' },
    { value: 5, label: '周五' },
    { value: 6, label: '周六' },
    { value: 7, label: '周日' },
  ];

  const monthOptions = Array.from({ length: 12 }, (_, i) => ({
    label: `${i + 1} 月`,
    value: i + 1,
  }));
  const dayOptions = Array.from({ length: 31 }, (_, i) => ({
    label: `${i + 1} 日`,
    value: i + 1,
  }));

  // ---- 类型切换：重置为默认配置（旧版 handleTaskTypeChange） ----
  function handleTypeChange(value: ParentTaskType | '') {
    emit('update:taskType', value);
    if (value === 'LIMITED') {
      emit('update:typeConfig', { end_date: '' });
    } else if (value === 'REPEAT') {
      emit('update:typeConfig', { frequency: 'DAILY' });
    } else if (value === 'STANDING') {
      emit('update:typeConfig', { max_submissions: null });
    } else {
      emit('update:typeConfig', {});
    }
  }

  // ---- LIMITED 子表单 ----
  const limitedStart = ref('');
  const limitedEnd = ref('');

  const limitedStartTs = computed(() => (limitedStart.value ? dayStart(limitedStart.value) : null));
  const limitedEndTs = computed(() => (limitedEnd.value ? dayStart(limitedEnd.value) : null));

  function dayStart(date: string): number {
    const ts = new Date(date + 'T00:00:00').getTime();
    return Number.isNaN(ts) ? 0 : ts;
  }

  function emitLimited(start: string | null, end: string | null) {
    limitedStart.value = start ?? '';
    limitedEnd.value = end ?? '';
    emit('update:typeConfig', {
      start_date: limitedStart.value || undefined,
      end_date: limitedEnd.value || undefined,
    });
  }

  // ---- REPEAT 子表单 ----
  type Frequency = 'DAILY' | 'WEEKLY' | 'MONTHLY' | 'YEARLY';
  const frequency = ref<Frequency>('DAILY');
  const weekday = ref<number | null>(null);
  const monthlyMode = ref('FIRST_DAY');
  const yearMonth = ref(1);
  const yearDay = ref(1);

  function buildRepeatConfig(
    freq: Frequency,
    wd: number | null,
    mm: string,
    ym: number,
    yd: number
  ): Record<string, unknown> {
    const cfg: Record<string, unknown> = { frequency: freq };
    if (freq === 'WEEKLY') {
      if (wd != null) cfg.trigger_day = { weekday: wd };
    } else if (freq === 'MONTHLY') {
      cfg.trigger_day = { mode: mm };
    } else if (freq === 'YEARLY') {
      cfg.trigger_day = { month: ym, day: yd };
    }
    return cfg;
  }

  function handleFrequencyChange(v: Frequency) {
    frequency.value = v;
    weekday.value = null;
    monthlyMode.value = 'FIRST_DAY';
    yearMonth.value = 1;
    yearDay.value = 1;
    emit('update:typeConfig', buildRepeatConfig(v, null, 'FIRST_DAY', 1, 1));
  }

  function handleWeekdayChange(day: number) {
    weekday.value = day;
    emit(
      'update:typeConfig',
      buildRepeatConfig(frequency.value, day, monthlyMode.value, yearMonth.value, yearDay.value)
    );
  }

  function handleMonthlyModeChange(v: string) {
    monthlyMode.value = v;
    emit(
      'update:typeConfig',
      buildRepeatConfig(frequency.value, weekday.value, v, yearMonth.value, yearDay.value)
    );
  }

  function emitYearly(ym: number, yd: number) {
    yearMonth.value = ym;
    yearDay.value = yd;
    emit(
      'update:typeConfig',
      buildRepeatConfig(frequency.value, weekday.value, monthlyMode.value, ym, yd)
    );
  }

  // ---- 外部 config 变化时同步本地状态（编辑回填） ----
  watch(
    () => [props.taskType, props.typeConfig] as const,
    () => {
      const cfg = props.typeConfig ?? {};
      // LIMITED
      limitedStart.value = (cfg.start_date as string) ?? '';
      limitedEnd.value = (cfg.end_date as string) ?? '';
      // REPEAT
      if (cfg.frequency) frequency.value = cfg.frequency as Frequency;
      const td = cfg.trigger_day;
      if (td && typeof td === 'object') {
        const obj = td as Record<string, unknown>;
        weekday.value = 'weekday' in obj ? Number(obj.weekday) || null : null;
        monthlyMode.value = 'mode' in obj ? (obj.mode as string) ?? 'FIRST_DAY' : 'FIRST_DAY';
        yearMonth.value = 'month' in obj ? Number(obj.month) || 1 : 1;
        yearDay.value = 'day' in obj ? Number(obj.day) || 1 : 1;
      } else {
        weekday.value = null;
        monthlyMode.value = 'FIRST_DAY';
        yearMonth.value = 1;
        yearDay.value = 1;
      }
      if (!cfg.frequency) frequency.value = 'DAILY';
    },
    { immediate: true, deep: true }
  );
</script>
